import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PostcardProvider } from "./providers/PostcardProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="js-focus-visible" data-js-focus-visible="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostcardProvider>
          {children}
        </PostcardProvider>
      </body>
    </html>
  );
}
